window.FALLBACK_MOVIES = [
  {
    "imdbID": "231035",
    "Title": "Violet Evergarden Movie",
    "Year": "2020",
    "Type": "Drama",
    "Poster": "https://cdn.myanimelist.net/images/anime/1825/110716.jpg",
    "description": "Han pasado varios años desde el final de la Primera Guerra Mundial. A medida que se sigue construyendo la torre de radio en Leidenschaftlich, los teléfonos pronto cobrarán mayor relevancia, lo que provocará una disminución en la demanda de \"Auto Memory Dolls\". Aun así, Violet Evergarden sigue en ascenso tras su éxito constante escribiendo cartas. Sin embargo, a veces lo único que anhelas es lo único que no aparece. La película Violet Evergarden sigue a Violet mientras continúa comprendiendo el concepto de la emoción y el significado del amor. Al mismo tiempo, busca un atisbo de esperanza: que el hombre que una vez le dijo \"Te amo\" pueda seguir vivo, incluso después de tantos años.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T23:39:05.023Z"
  },
  {
    "imdbID": "29082025",
    "Title": "Rápido y furioso",
    "Year": "2001",
    "Type": "Accion",
    "Poster": "https://hips.hearstapps.com/hmg-prod/images/fast-and-furious-1-1564933929.jpg?crop=1xw:1xh;center,top&resize=980:*",
    "description": "Una misteriosa banda de delincuentes se dedica a robar camiones en marcha desde vehículos deportivos. La policía decide infiltrar un hombre en el mundo de las carreras ilegales para descubrir posibles sospechosos. El joven y apuesto Brian entra en el mundo del tunning donde conoce a Dominic, rey indiscutible de este mundo y sospechoso número uno, pero todo se complicará cuando se enamore de su hermana.",
    "Ubication": "Guastatoya",
    "Estado": true,
    "Fec_Registro": "2025-08-29T23:00:29.773Z"
  },
  {
    "imdbID": "50",
    "Title": "Kingsman",
    "Year": "2014",
    "Type": "Acción",
    "Poster": "https://th.bing.com/th/id/R.65787ae015b3f841c132ebce37f68c7c?rik=3OLjiaJ2GIinQw&pid=ImgRaw&r=0",
    "description": "Cuando un agente secreto de Kingsman muere, su puesto es ocupado por otra persona. El resto de miembros debe proponer a un candidato, entre los cuales resultará elegido uno de ellos. En esta ocasión, el agente Galahad (Colin Firth) propone al hijo de un antiguo compañero: Eggsy (Taron Egerton). Mientras, el millonario Valentine (Samuel L. Jackson) tiene en mente un plan que pondría en riesgo a la mayor parte del planeta y los Kingsman deberán averiguar qué es y cómo evitarlo.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T21:12:22.900Z"
  },
  {
    "imdbID": "54",
    "Title": "50 SOMBRAS DE GREY",
    "Year": "2015",
    "Type": "MAYORES 18",
    "Poster": "https://es.web.img3.acsta.net/pictures/14/11/14/11/16/546987.jpg",
    "description": "PASION INTENSA GG",
    "Ubication": "GUASTATOYA",
    "Estado": true,
    "Fec_Registro": "2025-08-30T09:52:51.980Z"
  },
  {
    "imdbID": "5555555555",
    "Title": "El Conjuro 4",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://static.cinepolis.com/img/peliculas/50733/1/1/50733.jpg",
    "description": "El Conjuro: Último Ritos ofrece otro emocionante capítulo del icónico universo cinematográfico de El Conjuro, basado en hechos reales. Vera Farmiga y Patrick Wilson se reúnen para un último caso como los célebres investigadores paranormales de la vida real, Ed y Lorraine Warren, en una adición poderosa y escalofriante a la franquicia que rompe récords en taquilla global.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T09:33:27.783Z"
  },
  {
    "imdbID": "555562244",
    "Title": "Superman",
    "Year": "2025",
    "Type": "Acción/Suspenso",
    "Poster": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQFgxfqC60z1VjcC151bjgVNl9RhH9Tg6N8jDMkqQN0zsMCwLbV",
    "description": "Un superhéroe, se reconcilia con su herencia y su educación humana. Es la encarnación de la verdad, la justicia y un mañana mejor en un mundo que ve la bondad como algo anticuado.",
    "Ubication": "CHIMALTENANGO",
    "Estado": true,
    "Fec_Registro": "2025-08-30T10:59:55.683Z"
  },
  {
    "imdbID": "60",
    "Title": "Kingsman",
    "Year": "2014",
    "Type": "Acción",
    "Poster": "https://th.bing.com/th/id/R.65787ae015b3f841c132ebce37f68c7c?rik=3OLjiaJ2GIinQw&pid=ImgRaw&r=0",
    "description": "Cuando un agente secreto de Kingsman muere, su puesto es ocupado por otra persona. El resto de miembros debe proponer a un candidato, entre los cuales resultará elegido uno de ellos. En esta ocasión, el agente Galahad (Colin Firth) propone al hijo de un antiguo compañero: Eggsy (Taron Egerton). Mientras, el millonario Valentine (Samuel L. Jackson) tiene en mente un plan que pondría en riesgo a la mayor parte del planeta y los Kingsman deberán averiguar qué es y cómo evitarlo.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T21:13:42.150Z"
  },
  {
    "imdbID": "72344",
    "Title": "Shrek",
    "Year": "2004",
    "Type": "Infantil/Comedia",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQkYPkJwr8Ce5OCE_lAEqsdRwk8I4xF_phEA&s",
    "description": "Woody, el juguete favorito de Andy, se siente amenazado por la inesperada llegada de Buzz Lightyear, el guardián del espacio.",
    "Ubication": "POPCINEMA",
    "Estado": true,
    "Fec_Registro": "2025-08-30T00:18:31.517Z"
  },
  {
    "imdbID": "76542",
    "Title": "Toy Story",
    "Year": "1995",
    "Type": "Infantil/Comedia",
    "Poster": "https://media.tenor.com/XcBhzswyUV0AAAAM/e.gif",
    "description": "Woody, el juguete favorito de Andy, se siente amenazado por la inesperada llegada de Buzz Lightyear, el guardián del espacio....",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-30T00:13:47.053Z"
  },
  {
    "imdbID": "76543",
    "Title": " Megamente",
    "Year": "2010",
    "Type": "Infantil/Comedia",
    "Poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAh-kcOK1B-LDz8SCZaeX9Klrho15sgdiu0w&s",
    "description": "El super villano Megamente finalmente derrota a su némesis. Pero sin un héroe, pierde todo su propósito y debe dar un nuevo sentido a su vida.",
    "Ubication": "POPCINEMA",
    "Estado": true,
    "Fec_Registro": "2025-08-30T00:11:30.720Z"
  },
  {
    "imdbID": "80000",
    "Title": "Titanes del Atlantico ",
    "Year": "2014",
    "Type": "Ciencia Ficcion",
    "Poster": "https://imagenes.20minutos.es/files/image_640_auto/uploads/imagenes/2018/03/26/3135555.jpg",
    "description": "La humanidad se transforma en robots gigantes para defender la costa este de los monstruos que surgen del fondo del mar.",
    "Ubication": "POPCINEMA",
    "Estado": true,
    "Fec_Registro": "2025-08-28T11:09:12.260Z"
  },
  {
    "imdbID": "80005",
    "Title": "Iron Man: el hombre de hierro",
    "Year": "2008",
    "Type": "Acción",
    "Poster": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT95Db6V4jzEkaZjnWEV5n0qHu1a2InkUgafj3lWQDRxQIxYvL3",
    "description": "Tras haber estado cautivo en la celda afgana, el billonario ingeniero Tony Stark inventa un traje armado para luchar contra el mal.",
    "Ubication": "chimaltenango",
    "Estado": true,
    "Fec_Registro": "2025-08-30T10:28:34.590Z"
  },
  {
    "imdbID": "800096",
    "Title": "YOUR NAME",
    "Year": "2017",
    "Type": "DRAMA",
    "Poster": "https://meowmeowguatemala.com/wp-content/uploads/2023/03/Your-name-vol.01.jpg",
    "description": "Your Name.\" (Kimi no Na wa.) es una película de animación japonesa que narra la historia de Taki y Mitsuha, dos jóvenes que intercambian cuerpos inexplicablemente, uno en la ciudad y otro en el campo. La trama se desarrolla en torno a la búsqueda de una conexión a pesar de las barreras de tiempo y espacio, involucrando el destino, el amor y la memoria, todo ello aderezado con un desastre inminente que amenaza la vida de Mitsuha. ",
    "Ubication": "SANTA CLARA",
    "Estado": false,
    "Fec_Registro": "2025-08-28T23:45:32.860Z"
  },
  {
    "imdbID": "80012",
    "Title": "El Conjuro 4",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://punto.mx/wp-content/uploads/2025/05/El-conjuro-4-3.jpg",
    "description": "Cuando los investigadores paranormales Ed y Lorraine Warren se ven envueltos en otro aterrador caso relacionado con misteriosas criaturas, se ven obligados a resolverlo todo por última vez.",
    "Ubication": "Cinépolis Cayalá",
    "Estado": null,
    "Fec_Registro": "2025-08-29T19:56:12.853Z"
  },
  {
    "imdbID": "AL032",
    "Title": "RAPIDOS Y CURIOSOS",
    "Year": "2022",
    "Type": "Aventura",
    "Poster": "https://static.boredpanda.com/blog/wp-content/uploads/2020/02/super-bowl-ad-jason-momoa-rocket-mortgage-1-8-5e37c7d979e87__700.jpg",
    "description": "Entre mas rapidos, mas curiosos los pibes y con JASON MOMOA",
    "Ubication": "PORTALES",
    "Estado": true,
    "Fec_Registro": "2023-08-11T00:45:18.057Z"
  },
  {
    "imdbID": "ALL008",
    "Title": "Expediente Warren: El último rito",
    "Year": "2025",
    "Type": "HORROR",
    "Poster": "https://static.cinepolis.com/img/peliculas/50733/1/1/50733.jpg",
    "description": "El Conjuro: Último Ritos ofrece otro emocionante capítulo del icónico universo cinematográfico de El Conjuro, basado en hechos reales. Vera Farmiga y Patrick Wilson se reúnen para un último caso como los célebres investigadores paranormales de la vida real, Ed y Lorraine Warren, en una adición poderosa y escalofriante a la franquicia que rompe récords en taquilla global.",
    "Ubication": "OKLAN",
    "Estado": true,
    "Fec_Registro": "2025-09-09T17:07:20.453Z"
  },
  {
    "imdbID": "DV2003",
    "Title": "Jurassic World Rebirth",
    "Year": "2025",
    "Type": "Acción",
    "Poster": "https://dx35vtwkllhj9.cloudfront.net/universalstudios/jurassic-world-rebirth/images/regions/us/updates1/onesheet.jpg",
    "description": "Es una película que, cinco años después de Dominion, sigue a Zora Bennett (Scarlett Johansson), una exmilitar, en una misión secreta a la isla Ile Saint-Hubert para extraer ADN de tres colosales criaturas prehistóricas, buscando una cura para enfermedades cardíacas. En la isla, que alberga dinosaurios modificados y una instalación abandonada de InGen, el equipo de Zora se cruza con una familia y debe enfrentarse a un descubrimiento siniestro.",
    "Ubication": "Oakland mall",
    "Estado": true,
    "Fec_Registro": "2025-08-29T15:13:56.387Z"
  },
  {
    "imdbID": "FC508",
    "Title": "Destino Final: Lazos de sangre",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTlmNDRiZjgtNmYxNi00NTc3LWFlNzEtNzE0ZGQ1ODdlMDQ5XkEyXkFqcGc@._V1_.jpg",
    "description": "Destino final es una franquicia de terror estadounidense que incluye seis películas, diez novelas y dos cómics. Se basa en un guion no producido de Jeffrey Reddick, escrito originalmente para la serie de televisión The X-Files, y fue distribuida por New Line Cinema. ",
    "Ubication": "Aokland Mall",
    "Estado": true,
    "Fec_Registro": "2025-09-06T16:04:40.763Z"
  },
  {
    "imdbID": "FP903",
    "Title": "Sólo los valientes",
    "Year": "2017",
    "Type": "Acción/Suspenso",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMTkyNDk0NzEwOV5BMl5BanBnXkFtZTcwODAwMjc3Mg@@._V1_FMjpg_UX1000_.jpg",
    "description": "Basada en la conmovedora historia de los bomberos locales a quienes el heroísmo los conduce a la hermandad y al sacrificio.",
    "Ubication": "pradera",
    "Estado": true,
    "Fec_Registro": "2025-08-30T07:13:35.870Z"
  },
  {
    "imdbID": "IMDB1756402566519",
    "Title": "GODZILLA VS KONG",
    "Year": "2023",
    "Type": "Ciencia Ficción",
    "Poster": "https://play-lh.googleusercontent.com/W6HjfNo9I4UF4hTK2AE5ALRAUnR4mSOMsZAKb6WDiavnlSLHi6pDqmvL1hcKnPg9KamImKPIpb4DFq9jYA=w240-h480-rw",
    "description": "UNA RIVALIDAD ENTRE DOS GRANDES TITANES ",
    "Ubication": "GUASTATOYA",
    "Estado": true,
    "Fec_Registro": "2025-08-28T11:38:15.523Z"
  },
  {
    "imdbID": "IMDB1756496804097",
    "Title": "Godzilla Minus One",
    "Year": "2023",
    "Type": "Accion",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjc5MjllMGUtMDIwMS00ZDVkLWEzODQtM2NlMTMwMTZhNThmXkEyXkFqcGc@._V1_.jpg",
    "description": "Un monstruo gigante emerge de las profundidades del océano y se dispone a atacar Japón justo cuando la nación trata de recuperarse tras la destrucción ocasionada por la Segunda Guerra Mundial.",
    "Ubication": "OKLAN",
    "Estado": null,
    "Fec_Registro": "2025-08-29T13:47:18.230Z"
  },
  {
    "imdbID": "IMDB1756497810276",
    "Title": "Godzilla Minus One",
    "Year": "2023",
    "Type": "Accion",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjc5MjllMGUtMDIwMS00ZDVkLWEzODQtM2NlMTMwMTZhNThmXkEyXkFqcGc@._V1_.jpg",
    "description": "Un monstruo gigante emerge de las profundidades del océano y se dispone a atacar Japón justo cuando la nación trata de recuperarse tras la destrucción ocasionada por la Segunda Guerra Mundial.",
    "Ubication": "OKLAN",
    "Estado": null,
    "Fec_Registro": "2025-08-29T14:04:52.323Z"
  },
  {
    "imdbID": "IMDB1756497822290",
    "Title": "Labubu",
    "Year": "2025",
    "Type": "Accion",
    "Poster": "https://i.redd.it/w2acvughu3db1.jpg",
    "description": "This accion movie",
    "Ubication": "Guastatoya",
    "Estado": false,
    "Fec_Registro": "2025-08-29T14:04:52.760Z"
  },
  {
    "imdbID": "IMDB1756498357755",
    "Title": "Godzilla Minus One",
    "Year": "2023",
    "Type": "Accion",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjc5MjllMGUtMDIwMS00ZDVkLWEzODQtM2NlMTMwMTZhNThmXkEyXkFqcGc@._V1_.jpg",
    "description": "Un monstruo gigante emerge de las profundidades del océano y se dispone a atacar Japón justo cuando la nación trata de recuperarse tras la destrucción ocasionada por la Segunda Guerra Mundial.",
    "Ubication": "OKLAN",
    "Estado": null,
    "Fec_Registro": "2025-08-29T14:13:06.950Z"
  },
  {
    "imdbID": "IMDB1756511168687",
    "Title": "Shin Ultraman",
    "Year": "2020",
    "Type": "Accion",
    "Poster": "https://resizing.flixster.com/SCDmSMx-ibdLJFw1gP1OCsixGec=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p20623387_v_v13_ac.jpg",
    "description": "Tras la muerte accidental de un humano durante una batalla, Ultraman adopta la apariencia del hombre y su lugar en el Protocolo de Supresión de Especies Clase S para proteger a la Tierra de nuevas amenazas.",
    "Ubication": "OKLAN",
    "Estado": null,
    "Fec_Registro": "2025-08-29T17:46:49.607Z"
  },
  {
    "imdbID": "IMDB1756511388897",
    "Title": "Shin Ultraman",
    "Year": "2021",
    "Type": "Accion",
    "Poster": "https://resizing.flixster.com/SCDmSMx-ibdLJFw1gP1OCsixGec=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p20623387_v_v13_ac.jpg",
    "description": "",
    "Ubication": "OKLAN",
    "Estado": null,
    "Fec_Registro": "2025-08-29T17:50:23.870Z"
  },
  {
    "imdbID": "IMDB1756512022633",
    "Title": "Shin Ultraman",
    "Year": "2021",
    "Type": "Accion",
    "Poster": "https://resizing.flixster.com/SCDmSMx-ibdLJFw1gP1OCsixGec=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p20623387_v_v13_ac.jpg",
    "description": "Tras la muerte accidental de un humano durante una batalla, Ultraman adopta la apariencia del hombre y su lugar en el Protocolo de Supresión de Especies Clase S para proteger a la Tierra de nuevas amenazas.",
    "Ubication": "OKLAN",
    "Estado": true,
    "Fec_Registro": "2025-08-29T18:00:50.777Z"
  },
  {
    "imdbID": "IMDB1756512542553",
    "Title": "Godzilla Minus One",
    "Year": "2023",
    "Type": "Accion",
    "Poster": "https://m.media-amazon.com/images/M/MV5BMjc5MjllMGUtMDIwMS00ZDVkLWEzODQtM2NlMTMwMTZhNThmXkEyXkFqcGc@._V1_.jpg",
    "description": "Un monstruo gigante emerge de las profundidades del océano y se dispone a atacar Japón justo cuando la nación trata de recuperarse tras la destrucción ocasionada por la Segunda Guerra Mundial.",
    "Ubication": "lalapaluza",
    "Estado": true,
    "Fec_Registro": "2025-08-29T18:09:31.607Z"
  },
  {
    "imdbID": "IMDB1756526251985",
    "Title": "Pacific Rim",
    "Year": "2019",
    "Type": "Accion",
    "Poster": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p9360990_p_v12_at.jpg",
    "description": "Hace mucho tiempo, legiones de criaturas monstruosas llamados Kaiju surgen del mar, llevando consigo una guerra. Para pelear a los Kaiju, la humanidad desarrolla robots gigantes llamados Jaegers, diseñados para ser piloteados por dos humanos. Sin embargo, ni los Jaegers son suficientes para vencer a los Kaiju, y la humanidad está al borde de la derrota. La última esperanza de la humanidad descansa en un expiloto fracasado, un aprendiz y un viejo y obsoleto Jaeger.",
    "Ubication": "OKLAN",
    "Estado": true,
    "Fec_Registro": "2025-08-29T21:59:05.320Z"
  },
  {
    "imdbID": "LB740",
    "Title": "Los Simpson: La película",
    "Year": "2007",
    "Type": "Comedia/Aventura",
    "Poster": "https://images.justwatch.com/poster/307275623/s718/los-simpson-la-pelicula.jpg",
    "description": "La combinación de Homero, su nuevo puerco mascota y un silo lleno de excremento podrían provocar una catástrofe que no solo amenace a Springfield, sino a todo el mundo.",
    "Ubication": "PRADERA CHIMALTENANGO",
    "Estado": true,
    "Fec_Registro": "2025-08-30T21:28:44.047Z"
  },
  {
    "imdbID": "mjpa",
    "Title": "son como niños",
    "Year": "2001",
    "Type": "comedia",
    "Poster": "https://image.tmdb.org/t/p/original/poUK5Gg7IkPokaBTjadzjPfJgKw.jpg",
    "description": "es una comedia basada en un grupo de amigos",
    "Ubication": "miraflores",
    "Estado": true,
    "Fec_Registro": "2025-08-29T20:09:21.130Z"
  },
  {
    "imdbID": "NU265",
    "Title": "La Primera Vez Como Si Fuera",
    "Year": "2004",
    "Type": "Comedia/Romance",
    "Poster": "https://m.media-amazon.com/images/M/MV5BOWE0NjgxYjQtYTg5ZC00OWE2LWFmMjItZDdhODcwMmE3MGRkXkEyXkFqcGc@._V1_.jpg",
    "description": "Henry, biólogo marino, no tiene la mínima intención de comprometerse con nadie, hasta que conoce a Lucy, la chica de sus sueños. Sin embargo, hay un pequeño problema, la joven se levanta cada mañana sin recordar absolutamente nada del día anterior.",
    "Ubication": "ZONA PRADERA",
    "Estado": true,
    "Fec_Registro": "2025-08-29T20:47:09.907Z"
  },
  {
    "imdbID": "OR419",
    "Title": "Herbie a toda marcha",
    "Year": "2005",
    "Type": "Infantil/Comedia",
    "Poster": "https://image.tmdb.org/t/p/original/9h50ucJBO6hvtgWyyMxNmgOjsC1.jpg",
    "description": "El famoso Volkswagen, que tiene mente y sentimientos propios, ayuda a la alegre hija de un campeón de Nascar a triunfar en el automovilismo.",
    "Ubication": "PRADERA CHIMALTENANGO",
    "Estado": true,
    "Fec_Registro": "2025-08-29T21:14:03.557Z"
  },
  {
    "imdbID": "PR500",
    "Title": "ALARIDO",
    "Year": "2022",
    "Type": "Drama",
    "Poster": "https://static.cinepolis.com/img/peliculas/39933/1/1/39933.jpg",
    "description": "Una joven madre queda atrincherada dentro de la despensa de su casa en medio de la nada, dejando a sus dos pequeños bebés solos y expuestos a un escalofriante peligro. Deberá utilizar todo su ingenio, para protegerlos desde adentro mientras encuentra una forma de escapar.",
    "Ubication": "OKLAN",
    "Estado": false,
    "Fec_Registro": "2023-08-11T16:07:21.640Z"
  },
  {
    "imdbID": "PR902",
    "Title": "El Conjuro 4",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://static.cinepolis.com/img/peliculas/50733/1/1/50733.jpg",
    "description": "El Conjuro: Último Ritos ofrece otro emocionante capítulo del icónico universo cinematográfico de El Conjuro, basado en hechos reales. Vera Farmiga y Patrick Wilson se reúnen para un último caso como los célebres investigadores paranormales de la vida real, Ed y Lorraine Warren, en una adición poderosa y escalofriante a la franquicia que rompe récords en taquilla global.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T09:41:36.993Z"
  },
  {
    "imdbID": "PR9022",
    "Title": "El Conjuro 4",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://static.cinepolis.com/img/peliculas/50733/1/1/50733.jpg",
    "description": "El Conjuro: Último Ritos ofrece otro emocionante capítulo del icónico universo cinematográfico de El Conjuro, basado en hechos reales. Vera Farmiga y Patrick Wilson se reúnen para un último caso como los célebres investigadores paranormales de la vida real, Ed y Lorraine Warren, en una adición poderosa y escalofriante a la franquicia que rompe récords en taquilla global.",
    "Ubication": "POPCINEMA",
    "Estado": false,
    "Fec_Registro": "2025-08-29T09:50:31.063Z"
  },
  {
    "imdbID": "PR90222",
    "Title": "Superman 2",
    "Year": "2025",
    "Type": "Accion",
    "Poster": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQFgxfqC60z1VjcC151bjgVNl9RhH9Tg6N8jDMkqQN0zsMCwLbV",
    "description": "Superman 2",
    "Ubication": "Guastatoya",
    "Estado": false,
    "Fec_Registro": "2025-08-30T10:57:27.677Z"
  },
  {
    "imdbID": "ttj37dbermg",
    "Title": "El Conjuro 4: Últimos Ritos",
    "Year": "2025",
    "Type": "Terror",
    "Poster": "https://static.cinepolis.com/img/peliculas/50733/1/1/50733.jpg",
    "description": "El Conjuro: Último Ritos ofrece otro emocionante capítulo del icónico universo cinematográfico de El Conjuro, basado en hechos reales. Vera Farmiga y Patrick Wilson se reúnen para un último caso como los célebres investigadores paranormales de la vida real, Ed y Lorraine Warren, en una adición poderosa y escalofriante a la franquicia que rompe récords en taquilla global.",
    "Ubication": "OKLAN",
    "Estado": false,
    "Fec_Registro": "2025-08-29T09:10:19.160Z"
  },
  {
    "imdbID": "XI460",
    "Title": "Demon Slayer: MUGEN TRAIN",
    "Year": "2020",
    "Type": "Drama",
    "Poster": "https://m.media-amazon.com/images/M/MV5BOWRhMzU3YWEtYTlkMC00ZmUwLTk4ZmMtMDE2YTFlNDFiNjhmXkEyXkFqcGc@._V1_.jpg",
    "description": "Hola tanjuro ??",
    "Ubication": "Oklan",
    "Estado": true,
    "Fec_Registro": "2025-08-30T21:52:51.047Z"
  }
];